"""
Módulo de configuración del dashboard
"""

# ===== CONFIGURACIONES PRINCIPALES =====
from .settings import (
    DASHBOARD_CONFIG,
    DATA_FILES,
    CASOS_COLUMNS_MAP,
    EPIZOOTIAS_COLUMNS_MAP,
    GRUPOS_EDAD,
    CONDICION_FINAL_MAP,
    DESCRIPCION_EPIZOOTIAS_MAP,
    FILTROS_CONFIG,
    TABS_CONFIG,
    VERSION_INFO,
)

from .colors import (
    COLORS,
    COLOR_PALETTES,
    YELLOW_FEVER_COLORS,
)

# ===== EXPORTS =====
__all__ = [
    # Settings
    "DASHBOARD_CONFIG",
    "DATA_FILES", 
    "CASOS_COLUMNS_MAP",
    "EPIZOOTIAS_COLUMNS_MAP",
    "GRUPOS_EDAD",
    "CONDICION_FINAL_MAP",
    "DESCRIPCION_EPIZOOTIAS_MAP",
    "FILTROS_CONFIG",
    "TABS_CONFIG",
    "VERSION_INFO",
    
    # Colors
    "COLORS",
    "COLOR_PALETTES", 
    "YELLOW_FEVER_COLORS",
]